source: /
collections_config:
  src_content_blog:
    path: src/content/blog
    name: Src Content Blog
    icon: account_box
  src_data:
    path: src/data
    name: Src Data
    icon: chat
    disable_url: true
paths:
  static: public
  uploads: public/uploads
timezone: Africa/Cairo
markdown:
  engine: commonmark
  options:
    gfm: true
